apiVersion: v1
kind: PersistentVolume
metadata:
  name: dell-pv-001
  labels:
    type: local
spec:
  storageClassName: hdd
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: data-mysql-0
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: <nfs-server-path>
    server: <nfs-server-ip>